// On-watch WiFi setup: one field per screen with a large T9 keyboard.

use embedded_graphics::geometry::Point as EgPoint;
use embedded_graphics::mono_font::ascii::FONT_10X20;
use embedded_graphics::mono_font::MonoTextStyle;
use embedded_graphics::pixelcolor::Rgb565;
use embedded_graphics::prelude::*;
use embedded_graphics::primitives::{PrimitiveStyle, Rectangle, RoundedRectangle};
use embedded_graphics::text::{Alignment, Text};

use crate::peripherals::wifi::{WifiConfig, WifiState};
use crate::ui::t9_keyboard::T9Keyboard;

const ACTION_X: i32 = 278;
const ACTION_Y: i32 = 46;
const ACTION_W: u32 = 116;
const ACTION_H: u32 = 42;

#[derive(Clone, Copy, PartialEq)]
enum SetupStep {
    Ssid,
    Password,
    Review,
}

pub struct SettingsApp {
    pub wifi_config: WifiConfig,
    pub wifi_state: WifiState,
    pub keyboard: T9Keyboard,
    step: SetupStep,
    connection_request_pending: bool,
}

impl SettingsApp {
    pub fn new() -> Self {
        let mut keyboard = T9Keyboard::new();
        keyboard.show();
        Self {
            wifi_config: WifiConfig::new(),
            wifi_state: WifiState::Disconnected,
            keyboard,
            step: SetupStep::Ssid,
            connection_request_pending: false,
        }
    }

    fn action_hit(x: u16, y: u16) -> bool {
        (x as i32) >= ACTION_X
            && (x as i32) < ACTION_X + ACTION_W as i32
            && (y as i32) >= ACTION_Y
            && (y as i32) < ACTION_Y + ACTION_H as i32
    }

    fn save_active_field(&mut self) {
        match self.step {
            SetupStep::Ssid => self.wifi_config.set_ssid(self.keyboard.get_text()),
            SetupStep::Password => self.wifi_config.set_password(self.keyboard.get_text()),
            SetupStep::Review => {}
        }
    }

    fn edit_ssid(&mut self) {
        self.step = SetupStep::Ssid;
        self.keyboard.set_text(self.wifi_config.ssid_str());
        self.keyboard.show();
        self.wifi_state = WifiState::Disconnected;
    }

    fn edit_password(&mut self) {
        self.step = SetupStep::Password;
        self.keyboard.set_text(self.wifi_config.password_str());
        self.keyboard.show();
        self.wifi_state = WifiState::Disconnected;
    }

    /// Handle tap at screen position. Returns true if consumed.
    pub fn handle_tap(&mut self, x: u16, y: u16) -> bool {
        if self.wifi_state == WifiState::Connecting || self.wifi_state == WifiState::Connected {
            return true;
        }

        match self.step {
            SetupStep::Ssid => {
                if Self::action_hit(x, y) {
                    self.save_active_field();
                    if self.wifi_config.is_ready() {
                        self.edit_password();
                    } else {
                        self.wifi_state = WifiState::Error;
                    }
                    return true;
                }
                if self.keyboard.handle_tap(x, y) {
                    self.save_active_field();
                    self.wifi_state = WifiState::Disconnected;
                    return true;
                }
            }
            SetupStep::Password => {
                if Self::action_hit(x, y) {
                    self.save_active_field();
                    self.step = SetupStep::Review;
                    self.keyboard.hide();
                    self.wifi_state = WifiState::Disconnected;
                    return true;
                }
                if self.keyboard.handle_tap(x, y) {
                    self.save_active_field();
                    self.wifi_state = WifiState::Disconnected;
                    return true;
                }
            }
            SetupStep::Review => {
                if Self::action_hit(x, y) {
                    if self.wifi_config.is_ready() {
                        self.wifi_state = WifiState::Connecting;
                        self.connection_request_pending = true;
                    } else {
                        self.edit_ssid();
                        self.wifi_state = WifiState::Error;
                    }
                    return true;
                }
                // A large dedicated edit target avoids returning to a dense form.
                if (16..=394).contains(&(x as i32)) && (280..=355).contains(&(y as i32)) {
                    self.edit_password();
                    return true;
                }
                if (16..=394).contains(&(x as i32)) && (190..=265).contains(&(y as i32)) {
                    self.edit_ssid();
                    return true;
                }
            }
        }
        false
    }

    pub fn update(&mut self, dt_ms: u32) {
        if self.keyboard.update(dt_ms) {
            self.save_active_field();
        }
    }

    /// Consume the single request generated by the review screen's CONNECT action.
    pub fn take_connection_request(&mut self) -> bool {
        let requested = self.connection_request_pending;
        self.connection_request_pending = false;
        requested
    }

    fn action_label(&self) -> (&'static str, Rgb565) {
        match self.step {
            SetupStep::Ssid => ("NEXT", Rgb565::new(0, 20, 20)),
            SetupStep::Password => ("REVIEW", Rgb565::new(0, 20, 20)),
            SetupStep::Review => match self.wifi_state {
                WifiState::Error => ("RETRY", Rgb565::RED),
                _ => ("CONNECT", Rgb565::new(0, 20, 20)),
            },
        }
    }

    fn draw_action<D: DrawTarget<Color = Rgb565>>(&self, d: &mut D) {
        let (label, colour) = self.action_label();
        let _ = RoundedRectangle::with_equal_corners(
            Rectangle::new(EgPoint::new(ACTION_X, ACTION_Y), Size::new(ACTION_W, ACTION_H)),
            Size::new(12, 12),
        )
        .into_styled(PrimitiveStyle::with_fill(colour))
        .draw(d);
        let _ = Text::with_alignment(
            label,
            EgPoint::new(ACTION_X + ACTION_W as i32 / 2, ACTION_Y + 28),
            MonoTextStyle::new(&FONT_10X20, Rgb565::WHITE),
            Alignment::Center,
        )
        .draw(d);
    }

    fn draw_review<D: DrawTarget<Color = Rgb565>>(&self, d: &mut D) {
        let label = MonoTextStyle::new(&FONT_10X20, Rgb565::CSS_GRAY);
        let value = MonoTextStyle::new(&FONT_10X20, Rgb565::WHITE);
        let card = Rgb565::new(4, 9, 8);

        let _ = RoundedRectangle::with_equal_corners(
            Rectangle::new(EgPoint::new(16, 112), Size::new(378, 66)),
            Size::new(12, 12),
        )
        .into_styled(PrimitiveStyle::with_fill(card))
        .draw(d);
        let _ = Text::new("NETWORK", EgPoint::new(28, 136), label).draw(d);
        let ssid = self.wifi_config.ssid_str();
        let _ = Text::new(if ssid.is_empty() { "NOT SET" } else { ssid }, EgPoint::new(28, 160), value).draw(d);

        let _ = RoundedRectangle::with_equal_corners(
            Rectangle::new(EgPoint::new(16, 190), Size::new(378, 66)),
            Size::new(12, 12),
        )
        .into_styled(PrimitiveStyle::with_fill(card))
        .draw(d);
        let _ = Text::new("PASSWORD", EgPoint::new(28, 214), label).draw(d);
        let pass = if self.wifi_config.pass_len == 0 { "OPEN NETWORK" } else { "********" };
        let _ = Text::new(pass, EgPoint::new(28, 238), value).draw(d);

        let _ = RoundedRectangle::with_equal_corners(
            Rectangle::new(EgPoint::new(16, 280), Size::new(378, 62)),
            Size::new(12, 12),
        )
        .into_styled(PrimitiveStyle::with_fill(Rgb565::new(6, 12, 10)))
        .draw(d);
        let _ = Text::with_alignment("EDIT PASSWORD", EgPoint::new(205, 318), value, Alignment::Center).draw(d);
        let _ = Text::with_alignment("SESSION ONLY - NOT SAVED", EgPoint::new(205, 395), label, Alignment::Center).draw(d);
        let _ = Text::with_alignment("Tap a card to edit", EgPoint::new(205, 462), label, Alignment::Center).draw(d);
    }

    pub fn render<D: DrawTarget<Color = Rgb565>>(&self, d: &mut D) {
        let _ = Rectangle::new(EgPoint::zero(), Size::new(410, 502))
            .into_styled(PrimitiveStyle::with_fill(Rgb565::new(1, 2, 2)))
            .draw(d);

        let title = MonoTextStyle::new(&FONT_10X20, Rgb565::CYAN);
        let prompt = MonoTextStyle::new(&FONT_10X20, Rgb565::WHITE);
        let _ = Text::new("WI-FI SETUP", EgPoint::new(16, 34), title).draw(d);
        let heading = match self.step {
            SetupStep::Ssid => "1/3  ENTER NETWORK NAME",
            SetupStep::Password => "2/3  ENTER PASSWORD",
            SetupStep::Review => "3/3  REVIEW AND CONNECT",
        };
        let _ = Text::new(heading, EgPoint::new(16, 72), prompt).draw(d);
        self.draw_action(d);

        match self.step {
            SetupStep::Ssid | SetupStep::Password => self.keyboard.render(d),
            SetupStep::Review => self.draw_review(d),
        }

        if self.wifi_state == WifiState::Error {
            let error = MonoTextStyle::new(&FONT_10X20, Rgb565::RED);
            let message = if self.step == SetupStep::Ssid { "ENTER A NETWORK NAME" } else { "CONNECTION FAILED - EDIT OR RETRY" };
            let _ = Text::with_alignment(message, EgPoint::new(205, 96), error, Alignment::Center).draw(d);
        }
        if self.wifi_state == WifiState::Connecting || self.wifi_state == WifiState::Connected {
            let status = if self.wifi_state == WifiState::Connecting { "CONNECTING..." } else { "CONNECTED" };
            let colour = if self.wifi_state == WifiState::Connecting { Rgb565::YELLOW } else { Rgb565::GREEN };
            let _ = Text::with_alignment(status, EgPoint::new(205, 482), MonoTextStyle::new(&FONT_10X20, colour), Alignment::Center).draw(d);
        }
    }
}
